apiVersion: batch/v1
kind: Job
metadata:
  name: type-7-j
spec:
  template:
    spec:
      containers:
        - name: type-7-j
          image: docker.io/timattt/type-7-j:latest
          imagePullPolicy: Always
          env:
            - name: TYPE6_DATABASE_USER
              value: default-user
            - name: TYPE6_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_6_database_url
            - name: TYPE6_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_6_database_port
            - name: TYPE6_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_6_database_password
      restartPolicy: Never